### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by rohit-sourcefuse** [wankdanker/node-object-to-xml#3]
Try to converting this json into xml:
`{
  "status": true,
  "message": "all forms fields are capture successfully",
  "category": {
    "cid": 1,
    "cname": "Saree Blouse",
    "cdescription": null
  },
  "data": [
    {
      "id": 2,
      "field_name": "mmtname",
      "label": "measurment name",
      "order": 1,
      "isRequired": true,
      "mntguideImageUrl": null,
      "mntguideDesc": null,
      "minValue": 0,
      "maxValue": 0,
      "field": {
        "type": "text"
      },
      "values": {}
    },
    {
      "id": 3,
      "field_name": "aroundbust",
      "label": "around bust",
      "order": 3,
      "isRequired": true,
      "mntguideImageUrl": "http://www.udesign.in/images/mmt/around-bust.jpg",
      "mntguideDesc": "Take this measurement over the fullest part of the bust and across the widest part of the back. The measuring tape should go horizontally all around your body.",
      "minValue": 28,
      "maxValue": 66,
      "field": {
        "type": "range"
      },
      "values": {}
    },
    {
      "id": 10,
      "field_name": "sleevestyle",
      "label": "sleeve style",
      "order": 10,
      "isRequired": true,
      "mntguideImageUrl": null,
      "mntguideDesc": null,
      "minValue": 0,
      "maxValue": 0,
      "field": {
        "type": "options"
      },
      "values": [
        {
          "id": 55,
          "value": "SLEEVELESS",
          "imagepath": "http://",
          "impactedField": null,
          "impactedFieldMinValue": 0,
          "impactedFieldMaxValue": 0,
          "desc": null
        },
        {
          "id": 56,
          "value": "EXTRA SLIM SLEEVELESS",
          "imagepath": "http://",
          "impactedField": null,
          "impactedFieldMinValue": 0,
          "impactedFieldMaxValue": 0,
          "desc": null
        },
        {
          "id": 57,
          "value": "CAP SLEEVE",
          "imagepath": "http://",
          "impactedField": null,
          "impactedFieldMinValue": 0,
          "impactedFieldMaxValue": 0,
          "desc": null
        },
        {
          "id": 58,
          "value": "SHORT SLEEVE",
          "imagepath": "http://",
          "impactedField": null,
          "impactedFieldMinValue": 0,
          "impactedFieldMaxValue": 0,
          "desc": null
        },
        {
          "id": 59,
          "value": "ARMBAND",
          "imagepath": "http://",
          "impactedField": null,
          "impactedFieldMinValue": 0,
          "impactedFieldMaxValue": 0,
          "desc": null
        },
        {
          "id": 60,
          "value": "WIDE STRAP",
          "imagepath": "http://",
          "impactedField": null,
          "impactedFieldMinValue": 0,
          "impactedFieldMaxValue": 0,
          "desc": null
        },
        {
          "id": 61,
          "value": "NOODLE STRAP",
          "imagepath": "http://",
          "impactedField": null,
          "impactedFieldMinValue": 0,
          "impactedFieldMaxValue": 0,
          "desc": null
        }
      ]
    },
    {
      "id": 13,
      "field_name": "topclosingside",
      "label": "closing side",
      "order": 13,
      "isRequired": true,
      "mntguideImageUrl": null,
      "mntguideDesc": null,
      "minValue": 0,
      "maxValue": 0,
      "field": {
        "type": "options"
      },
      "values": [
        {
          "id": 62,
          "value": "Front",
          "imagepath": "",
          "impactedField": null,
          "impactedFieldMinValue": 0,
          "impactedFieldMaxValue": 0,
          "desc": null
        },
        {
          "id": 63,
          "value": "Back",
          "imagepath": "",
          "impactedField": null,
          "impactedFieldMinValue": 0,
          "impactedFieldMaxValue": 0,
          "desc": null
        },
        {
          "id": 64,
          "value": "Side",
          "imagepath": "",
          "impactedField": null,
          "impactedFieldMinValue": 0,
          "impactedFieldMaxValue": 0,
          "desc": null
        }
      ]
    }
  ]
}`

**And Getting this issue** :
Unhandled rejection RangeError: **Maximum call stack size exceeded**
    at RegExp.test (native)
    at ~/node_modules/object-to-xml/index.js:42:19
    at doCall (~/node_modules/dank-map/index.js:93:14)
    at map (~/node_modules/dank-map/index.js:70:4)
    at objectToXML (~/node_modules/object-to-xml/index.js:9:2)
    at Object.<anonymous> (~/node_modules/object-to-xml/index.js:61:14)
    at doCall (~/node_modules/dank-map/index.js:93:14)
    at map (~/node_modules/dank-map/index.js:70:4)
    at objectToXML (~/node_modules/object-to-xml/index.js:9:2)
    at null.<anonymous> (~/node_modules/object-to-xml/index.js:61:14)
    at doCall (~/node_modules/dank-map/index.js:93:14)
    at map (~/node_modules/dank-map/index.js:70:4)
    at objectToXML (~/node_modules/object-to-xml/index.js:9:2)
    at null.<anonymous> (~/node_modules/object-to-xml/index.js:61:14)
    at doCall (~/node_modules/dank-map/index.js:93:14)
    at map (~/node_modules/dank-map/index.js:70:4)

**Comment by rohit-sourcefuse** [comment]
Closing this issue found some json input issue in debugging.
